export type Track = "software" | "hardware" | "wildcard" | "creatives";
export type Cohort = 0 | 2 | 3 | 4;

export type Project = {
  projectName: string;
  creatorName: string;
  track: Track;
  cohort: Cohort;
  description: string;
  demoLink: string;
  coverImage: string;
  longDescription: string;
  details: { tech: string[] };
  gallery?: string[];
  featured?: boolean;
};

// ==================== COHORT 4 ====================
export const cohort4Projects: Project[] = [
  {
    projectName: "Mindspace",
    creatorName: "Abdul Muhsin Hameed",
    track: "software" as const,
    cohort: 4,
    description: "The civilian, good guy version of tron: ares.",
    demoLink: "https://muhsinh.github.io/mind.space/",
    coverImage: "/images/projects/mindspace.png",
    longDescription: "A transparent safety layer for AI therapy.",
    details: { tech: ["React", "Vite", "TailwindCSS", "JavaScript", "Python", "Shell"] }, 
    gallery: ["/images/projects/mindspace.png", "/images/projects/mindspace1.png", "/images/projects/mindspace2.png"],
    featured: false
  },
  {
    projectName: "Checkpoint",
    creatorName: "Tisya Bhatia",
    track: "software" as const,
    cohort: 4,
    description: "Helping neurodivergent users stay focused with dopamine-boost activities and AI.",
    demoLink: "https://checkpoint-fitness-cjxvojvgz-tisya-bhatias-projects.vercel.app/",
    coverImage: "/images/projects/checkpoint.png",
    longDescription: "Uses progressive overload, overall training volume & gain strengths, and lots of exercises to help boost your fitness.",
    details: { tech: ["React", "Vite", "Vision API", "JavaScript", "Python"] }, 
    gallery: ["/images/projects/checkpoint.png", "/images/projects/checkpoint-1.png", "/images/projects/checkpoint1.png", "/images/projects/checkpoint2.png", "/images/projects/checkpoint3.png", "/images/projects/checkpoint4.png"],
    featured: true
  },
  {
    projectName: "RareCare Pipeline",
    creatorName: "Douglas Lin & Andy Hou",
    track: "software" as const,
    cohort: 4,
    description: "Medical pipeline that analyzes symptoms, runs targeted tests, and suggests potential treatments for rare diseases.",
    demoLink: "https://variant-intel.streamlit.app/",
    coverImage: "/images/projects/med2.png",
    longDescription: "Medical pipeline that analyzes symptoms, runs targeted tests, and suggests potential treatments for rare diseases.",
    details: { tech: ["Python", "Streamlit"] }, 
    gallery: ["/images/projects/med2.png", "/images/projects/med1.png", "/images/projects/med.png"],
    featured: false
  },
  {
    projectName: "dawgdig",
    creatorName: "Joshua Ton",
    track: "software" as const,
    cohort: 4,
    description: "UW student focused planner and rso/event discovery web app.",
    demoLink: "https://dawgdig.vercel.app/",
    coverImage: "/images/projects/dawg.png",
    longDescription: "A UW focused app dedicated to help students find RSOs and events that they actually care about and organize it all in one place.",
    details: { tech: ["React", "Spring Boot"] }, 
    gallery: ["/images/projects/dawg1.png", "/images/projects/dawg2-2.png", "/images/projects/dawg3-2.png", "/images/projects/dawg4-2.png", "/images/projects/dawg5-2.png"],
    featured: true
  },
  {
    projectName: "EcoScan",
    creatorName: "Nandini Khandelwal",
    track: "software" as const,
    cohort: 4,
    description: "A tool that analyzes a user’s AI usage and shows its environmental impact.",
    demoLink: "",
    coverImage: "/images/projects/eco1.png",
    longDescription: "A tool that analyzes a user’s AI usage and shows its environmental impact.",
    details: { tech: ["React", "Python"] }, 
    gallery: ["/images/projects/eco2.png", "/images/projects/eco1.png", "/images/projects/eco.png"],
    featured: false
  },
  {
    projectName: "Sensei",
    creatorName: "Sahana Narendran",
    track: "software" as const,
    cohort: 4,
    description: "A smart timesheet for self-employed side hustlers.",
    demoLink: "",
    coverImage: "/images/projects/sensei.png",
    longDescription: "A smart timesheet for self-employed side hustlers.",
    details: { tech: ["Lovable", "Cursor"] }, 
    gallery: ["/images/projects/sensei.png", "/images/projects/sensei2.png", "/images/projects/sensei3.png"],
    featured: false
  },
  {
    projectName: "Itinderary",
    creatorName: "Chloe Bogen",
    track: "software" as const,
    cohort: 4,
    description: "Swipe through Seattle activities and auto-builds a personalized itinerary, tinder-style.",
    demoLink: "/images/projects/itinderary.mp4",
    coverImage: "/images/projects/itinderary.mp4",
    longDescription: "Swipe through Seattle activities and auto-builds a personalized itinerary, tinder-style.",
    details: { tech: ["React", "Vite", "OpenAI API"] }, 
    gallery: ["/images/projects/itinderary.png", "/images/projects/itinderary2.png"],
    featured: false
  },
  {
    projectName: "Train of Thought",
    creatorName: "Dhanasri Prabhu, Devanshi Rautraya, and Rishali Vuriti",
    track: "software" as const,
    cohort: 4,
    description: "An adaptive Trolley Problem Simulator.",
    demoLink: "/images/projects/trolley.mp4",
    coverImage: "/images/projects/trolley3.png",
    longDescription: "An adaptive Trolley Problem Simulator.",
    details: { tech: ["Google Gemini", "HTML", "CSS", "JavaScript"] }, 
    gallery: ["/images/projects/trolley.png", "/images/projects/trolley2.png"],
    featured: false
  },
  {
    projectName: "LandDev Map",
    creatorName: "Advaith Vankamamidi",
    track: "software" as const,
    cohort: 4,
    description: "Interactive map that helps make land-development decisions more informed.",
    demoLink: "",
    coverImage: "/images/projects/land1.png",
    longDescription: "Interactive map that shows zoning, environmental rules, utilities to make land-development decisions more informed.",
    details: { tech: ["Python", "OpenCV", "PyVista"] }, 
    gallery: ["/images/projects/land.png", "/images/projects/land1.png"],
    featured: false
  },
  {
    projectName: "Hermopolis",
    creatorName: "Nikki Mihaylova",
    track: "software" as const,
    cohort: 4,
    description: "A community where you can upload, translate, discuss, and nerd out about quotes in any language.",
    demoLink: "https://linktr.ee/hermopolisblog",
    coverImage: "/images/projects/herm2.png",
    longDescription: "A community where you can upload, translate, discuss, and nerd out about quotes in any language.",
    details: { tech: ["Firebase", "HTML", "JavaScript", "CSS", "Figma"] }, 
    gallery: ["/images/projects/herm2.png", "/images/projects/herm1.png", "/images/projects/herm.png"],
    featured: false
  },
  {
    projectName: "You Will Always Get Through",
    creatorName: "Samvedha Basireddy",
    track: "software" as const,
    cohort: 4,
    description: "Short, personalized micro-rituals to help people reset during stressful moments.",
    demoLink: "",
    coverImage: "/images/projects/meditate1.png",
    longDescription: "Short, personalized micro-rituals to help people reset during stressful moments.",
    details: { tech: ["React", "Vite", "TailwindCSS", "TypeScript"] }, 
    gallery: ["/images/projects/meditate1.png", "/images/projects/meditate.png", "/images/projects/meditate2.png"],
    featured: false
  },
  {
    projectName: "Access Map",
    creatorName: "Neha Dubhashi, Daniel Welicki, Cady Xia, and Trisha Bhatawdekar",
    track: "software" as const,
    cohort: 4,
    description: "Accessibility details for campus events for students with disabilities.",
    demoLink: "",
    coverImage: "/images/projects/access.png",
    longDescription: "Accessibility details for campus events for students with disabilities.",
    details: { tech: ["Expo", "Android Studio"] }, 
    gallery: ["/images/projects/access2.png", "/images/projects/access1.png", "/images/projects/access.png"],
    featured: false
  },
  {
    projectName: "Plink: Piano Map",
    creatorName: "Benito Correa",
    track: "software" as const,
    cohort: 4,
    description: "Map of public pianos and with rating details like tuning, access, and condition.",
    demoLink: "/images/projects/plink.mp4",
    coverImage: "/images/projects/plink1.png",
    longDescription: "",
    details: { tech: ["React", "TailwindCSS", "Vite", "TypeScript", "Firebase", "Howler.js"] }, 
    gallery: ["/images/projects/plink1.png", "/images/projects/plink.png", "/images/projects/checkpoint-1.png"],
    featured: false
  },
  {
    projectName: "Citesy",
    creatorName: "Dulguun Uuganbaatar",
    track: "creatives" as const,
    cohort: 4,
    description: "Citation generator for written work.",
    demoLink: "/images/projects/citesy.mp4",
    coverImage: "/images/projects/citesy0.png",
    longDescription: "Citation generator for written work.",
    details: { tech: ["HTML", "Python", "API"] }, 
    gallery: ["/images/projects/citesy0.png", "/images/projects/citesy2.png", "/images/projects/citesy2.png", "/images/projects/citesy.mp4"],
    featured: false
  },
  {
    projectName: "Kyusoku App",
    creatorName: "Jake Wicke",
    track: "software" as const,
    cohort: 4,
    description: "Turns highlighted Japanese words into instant flashcards without interrupting your reading.",
    demoLink: "",
    coverImage: "/images/projects/kyu.png",
    longDescription: "Turns highlighted Japanese words into instant flashcards without interrupting your reading.",
    details: { tech: ["AWS", "Ajax", "JavaScript", "HTML", "CSS"] }, 
    gallery: ["/images/projects/kyu.png", "/images/projects/kyu2.png", "/images/projects/kyu3.png", "/images/projects/kyu4.png"],
    featured: false
  },
  {
    projectName: "Claverito Scavenger Hunt Map",
    creatorName: "Selena Liu",
    track: "creatives" as const,
    cohort: 4,
    description: "A printed scavenger hunt map for visitors to get to know Claverito, a floodplain community in Peru.",
    demoLink: "",
    coverImage: "/images/projects/peru.png",
    longDescription: "A printed scavenger hunt map for visitors to get to know Claverito, a floodplain community in Peru, better.",
    details: { tech: ["Figma", "Canva"] }, 
    gallery: ["/images/projects/peru.png", "/images/projects/peru4.png", "/images/projects/peru5.png", "/images/projects/peru2.png", "/images/projects/peru3.png"],
    featured: false
  },
  {
    projectName: "AutoFetcher",
    creatorName: "Wallace Ruan",
    track: "hardware" as const,
    cohort: 4,
    description: "A contraption that automatically shoots a ball for a dog to fetch.",
    demoLink: "/images/projects/fetch.mp4",
    coverImage: "/images/projects/fetch2.png",
    longDescription: "A contraption that automatically shoots a ball for a dog to fetch.",
    details: { tech: ["PVC Pipe", "Cardboard", "Tire", "Compression Spring"] }, 
    gallery: ["/images/projects/fetch2.png", "/images/projects/fetch.png", "/images/projects/fetch.mp4"],
    featured: true
  },
  {
    projectName: "RagaID",
    creatorName: "Suraj Shivakumar",
    track: "software" as const,
    cohort: 4,
    description: "AI tool that listens to Indian classical music and identifies the raga.",
    demoLink: "",
    coverImage: "/images/projects/raga0.png",
    longDescription: "AI tool that listens to Indian classical music and identifies the raga - like Shazam but for Carnatic compositions",
    details: { tech: ["Python", "Dunya API", "CRNN"] }, 
    gallery: ["/images/projects/raga0.png", "/images/projects/raga2.png", "/images/projects/raga3.png", "/images/projects/raga4.png", "/images/projects/raga5.png", "/images/projects/raga.png", "/images/projects/raga1.png"],
    featured: false
  },
  {
    projectName: "Graham's Youtube",
    creatorName: "Graham Cobden",
    track: "creatives" as const,
    cohort: 4,
    description: "Channel with about cool things Graham does and finds interesting.",
    demoLink: "https://www.youtube.com/shorts/M_K3L8nIwTU",
    coverImage: "/images/projects/graham.png",
    longDescription: "Channel with about cool things Graham does and finds interesting.",
    details: { tech: ["YouTube"] }, 
    gallery: ["/images/projects/graham.png", "/images/projects/yt.png", "/images/projects/yt1.png"],
    featured: false
  },
  {
    projectName: "Shui-ify - Feng Shui Your Room",
    creatorName: "Thomas Wang, Shiven Friedeman, and William Dinh",
    track: "software" as const,
    cohort: 4,
    description: "Arrange your room using feng shui principles.",
    demoLink: "https://www.youtube.com/watch?v=viFyMBvne8E&t=2s",
    coverImage: "/images/projects/feng2.png",
    longDescription: "Arrange your room using feng shui principles by generating an optimized layout based on your furniture and space.",
    details: { tech: ["PulP python"] }, 
    gallery: ["/images/projects/feng2.png", "/images/projects/feng3.png", "/images/projects/feng.png", "/images/projects/feng1.png"],
    featured: false
  },
  {
    projectName: "Silhouette",
    creatorName: "Surya Duraivenkatesh & Shiloh Dhasan",
    track: "software" as const,
    cohort: 4,
    description: "Tiny LiDAR sensors that maps how customers move in small stores.",
    demoLink: "https://colab.research.google.com/drive/1_eSzbMg9M51AQp_5JrGCWMciLskr6w2H?usp=sharing",
    coverImage: "/images/projects/sil0.png",
    longDescription: "Tiny LiDAR sensors that maps how customers move in small stores and generates heat maps with layout suggestions.",
    details: { tech: ["Google Colab", "Python"] }, 
    gallery: ["/images/projects/sil.png", "/images/projects/sil1.png", "/images/projects/sil3.png", "/images/projects/sil2.png"],
    featured: false
  },
  {
    projectName: "Smart Funds",
    creatorName: "Raika Roy Choudhury",
    track: "software" as const,
    cohort: 4,
    description: "Web app that teaches college students financial literacy.",
    demoLink: "https://v0-smart-funds-gamification-demo.vercel.app/",
    coverImage: "/images/projects/smartfunds.png",
    longDescription: "Web app that teaches college students financial literacy.",
    details: { tech: ["React", "Next.js", "TailwindCSS", "TypeScript"] }, 
    gallery: ["/images/projects/smartfunds.png", "/images/projects/fund1.png", "/images/projects/fund0.png"],
    featured: false
  },
  {
    projectName: "Talunt",
    creatorName: "Avi Agola",
    track: "software" as const,
    cohort: 4,
    description: "AI-powered recruiting platform that sources, screens, and schedules candidates with transparent feedback.",
    demoLink: "https://app.talunt.io",
    coverImage: "/images/projects/talunt.png",
    longDescription: "AI-powered recruiting platform that sources, screens, and schedules candidates with transparent feedback.",
    details: { tech: ["React", "Next.js", "TypeScripte"] }, 
    gallery: ["/images/projects/talunt0.png", "/images/projects/talunt1.png", "/images/projects/talunt2.png", "/images/projects/talunt3.png", "/images/projects/talunt4.png"],
    featured: false
  },
  {
    projectName: "Yomi Sensei",
    creatorName: "Keanu Thakalath",
    track: "software" as const,
    cohort: 4,
    description: "An e-reader that automatically tracks your reading level.",
    demoLink: "/images/projects/yomi.mp4",
    coverImage: "/images/projects/yomi0.png",
    longDescription: "An e-reader that automatically tracks your reading level.",
    details: { tech: ["Mecab", "Aozora Bunko"] }, 
    gallery: ["/images/projects/yomi0.png", "/images/projects/yomi1.png"],
    featured: true
  },
  {
    projectName: "HeartBeats",
    creatorName: "Hriesha Popat & Saachi Dhamija",
    track: "software" as const,
    cohort: 4,
    description: "Matches your real-time heart rate to music and auto-creates playlists that fit your workout energy.",
    demoLink: "/images/projects/beats.mp4",
    coverImage: "/images/projects/beats.png",
    longDescription: "Matches your real-time heart rate to music and auto-creates playlists that fit your workout energy.",
    details: { tech: ["Swift", "Python", "k-NN algorithm"] }, 
    gallery: ["/images/projects/beats.png", "/images/projects/beats1.png", "/images/projects/beats3.png", "/images/projects/beats2.png"],
    featured: true
  },
  {
    projectName: "GenreVision",
    creatorName: "Tanush Ganji",
    track: "software" as const,
    cohort: 4,
    description: "Predicts the genre of a song given an mp3/wav and gather statistics that shows visualized data.",
    demoLink: "",
    coverImage: "/images/projects/genre.png",
    longDescription: "Predicts the genre of a song given an mp3/wav and gather statistics that shows visualized data.",
    details: { tech: ["Streamlit", "Python", "Tensorflow", "PyTorch"] }, 
    gallery: ["/images/projects/genre.png", "/images/projects/genre1.png", "/images/projects/genre2.png", "/images/projects/genre2.png"],
    featured: false
  },
  {
    projectName: "Husky Space",
    creatorName: "Ahana Mangla",
    track: "software" as const,
    cohort: 4,
    description: "A platform for dorm students to help find community, stay updated on events, and manage communal spaces.",
    demoLink: "",
    coverImage: "/images/projects/space.png",
    longDescription: "A platform for dorm students to help find community, stay updated on events, and manage communal spaces.",
    details: { tech: ["Flutterflow", "Figma", "Firestore"] }, 
    gallery: ["/images/projects/space.png", "/images/projects/space1.png", "/images/projects/space2.png", "/images/projects/space2.png", "/images/projects/space3.png", "/images/projects/space4.png"],
    featured: false
  },
  {
    projectName: "Click",
    creatorName: "Kairui Cheng, Matthew Epshtein, and Rayan Rizwan",
    track: "software" as const,
    cohort: 4,
    description: "App that lets students “tap phones” to create connection bridges.",
    demoLink: "https://click-us.vercel.app/",
    coverImage: "/images/projects/click.png",
    longDescription: "App that lets students “tap phones” to create connection bridges and pairs them for short conversations to build real friendships.",
    details: { tech: ["Kotlin Compose", "Python", "Mongo", "Supabase"] }, 
    gallery: ["/images/projects/click1.png", "/images/projects/click3.png", "/images/projects/click4.png", "/images/projects/click2.png"],
    featured: true
  }
];

// ==================== COHORT 3 ====================
export const cohort3Projects: Project[] = [
  {
    projectName: "Jam Journal",
    creatorName: "Jenny Peng & Kelly Wang",
    track: "creatives" as const,
    cohort: 3,
    description: "A song annotation platform",
    demoLink: "https://drive.google.com/file/d/1vFHSItXw6BIRBEEMULdq2UdgEFEAfq6_/view",
    coverImage: "/images/projects/jamjournal.png",
    longDescription: "A platform to import YouTube music, take notes at timestamps while listening, and make notes for lyrics.",
    details: { tech: ["React", "Next.js", "HTML", "Figma"] }, 
    gallery: ["/images/projects/jamjournal.png", "/images/projects/jam2.png"],
    featured: true
  },
  {
    projectName: "MarioKart Racecar",
    creatorName: "Mukund Senthil Kumar",
    track: "hardware",
    cohort: 3,
    description: "An automated racecar that uses different sensors to traverse the terrain.",
    demoLink: "/images/projects/racecar.mp4",
    coverImage: "/images/projects/racecar.png",
    longDescription: "An automated racecar that uses different sensors to traverse the terrain and not hit obstacles and pedestrians.",
    details: { tech: ["Raspberry Pi 4", "Servo Motor", "Brushed Motor", "Wide Angled Camera", "PCA9685 PWM Servo Driver Board"] },
    gallery: ["/images/projects/racecar.png", "/images/projects/racecar.mp4"],
    featured: true
  },
  {
    projectName: "2048 Agent",
    creatorName: "Brian Yao",
    track: "software",
    cohort: 3,
    description: "An Ai agent that plays the game 2048.",
    demoLink: "/images/projects/2048-2.mp4",
    coverImage: "/images/projects/2048.mp4",
    longDescription: "Using reinforcement learning (DQN and PPO), and expectimax, the agent can predict and perform the most optimal moves in 2048.",
    details: { tech: ["DQN", "PPO", "2048"] },
    gallery: ["/images/projects/2048.png", "/images/projects/2048-2.png", "/images/projects/2048-3.png", "/images/projects/2048-4.png", "/images/projects/2048.mp4", "/images/projects/2048-2.mp4"],
    featured: true
  },
  {
    projectName: "Verbalize",
    creatorName: "Medha Gupta",
    track: "software",
    cohort: 3,
    description: "An AI-powered multiplayer game that makes behavioral interview prep fun and approachable.",
    demoLink: "https://verbalizeprep.com/landing",
    coverImage: "/images/projects/verbalize.png",
    longDescription: "An AI-powered multiplayer game that makes behavioral interview prep fun and approachable.",
    details: { tech: ["Lucid"] },
    gallery: ["/images/projects/verbalize.png", "/images/projects/verbalize1.png", "/images/projects/verbalize2.png", "/images/projects/verbalize2.png"],
    featured: true
  },
  {
    projectName: "Smile w/ me",
    creatorName: "Eva Gonzales-Bravo",
    track: "software",
    cohort: 3,
    description: "A photo booth website where you can take pics and have fun!",
    demoLink: "/images/projects/smile.mp4",
    coverImage: "/images/projects/smile.png",
    longDescription: "This is a hand-coded photo booth website, where you can take photos and add stickers and filters!",
    details: { tech: ["HTML", "CSS", "React"] },
    gallery: ["/images/projects/smile.png", "/images/projects/smile.mp4"],
    featured: false
  },
  {
    projectName: "Juicebox",
    creatorName: "Sia Razdan",
    track: "creatives",
    cohort: 3,
    description: "Rewards families for disconnecting from screens - enabling connection, learning, and fun.",
    demoLink: "/images/projects/juicebox.mp4",
    coverImage: "/images/projects/juicebox.png",
    longDescription: "This is a design speculative project to foster connection and disconnecting from screens.",
    details: { tech: ["Figma", "Design", "Wireframing"] },
    gallery: ["/images/projects/juicebox.png", "/images/projects/juicebox.mp4"],
    featured: false
  },
  {
    projectName: "Fridge Sense",
    creatorName: "Shrima & Arya",
    track: "software",
    cohort: 3,
    description: "Smart food tracking app for your fridge, creating an easy way to track food expiry dates and reduce waste.",
    demoLink: "/images/projects/fridge.mp4",
    coverImage: "/images/projects/fridge.png",
    longDescription: "A handy tool for knowing what's in your fridge, helps with grocery shopping. Helps combat food waste at the college level!",
    details: { tech: ["React", "Google Firebase", "Sqlite", "Flask", "APIs", "Figma" ] },
    gallery: ["/images/projects/fridge.png", "/images/projects/fridge.mp4"],
    featured: false
  },
  {
    projectName: "Gladius",
    creatorName: "Alex Hsu",
    track: "creatives",
    cohort: 3,
    description: "Can't grow your plants without growing your muscles.",
    demoLink: "/images/projects/gladius.mp4",
    coverImage: "/images/projects/gladius.png",
    longDescription: "A plant-themed app that motivates fitness through digital garden growth. Gladius transforms your fitness journey into a motivational experience. It tracks your progress through biometric data.",
    details: { tech: ["Spline", "Figma" ] },
    gallery: ["/images/projects/gladius.png", "/images/projects/gladius.mp4"],
    featured: false
  },
  {
    projectName: "Se7en",
    creatorName: "Noah Hoang, Kshitij Rao, and Chetan Sidhu",
    track: "software",
    cohort: 3,
    description: "An app that fosters UW connectivity and community.",
    demoLink: "/images/projects/seven.mp4",
    coverImage: "/images/projects/seven.png",
    longDescription: "Se7en effortlessly organizes groups of people with similar interests for casual convos/coffee chat-like conversations.",
    details: { tech: ["ROS", "Computer Vision", "GPS", "LiDAR"] },
    gallery: ["/images/projects/seven.png", "/images/projects/seven.mp4"],
    featured: false
  },
  {
    projectName: "Nivo",
    creatorName: "Samantha Scalia",
    track: "hardware",
    cohort: 3,
    description: "Goggles designed for comfort and adaptability, delivering a clear and unobstructed view.",
    demoLink: "/images/projects/nivo.mp4",
    coverImage: "/images/projects/nivo.png",
    longDescription: "Prescription lenses, custom fit, all-weather performance, and comfort. The base model is a simple CAD model that can be adjusted to the user's measurements.",
    details: { tech: ["CAD", "Figma", "TPU"] },
    gallery: ["/images/projects/nivo.png", "/images/projects/nivo.mp4"],
    featured: false
  },
  {
    projectName: "Content Creation",
    creatorName: "Tiffany Yan",
    track: "creatives",
    cohort: 3,
    description: "Building my content creation through Instagram, LinkedIn, and Notion.",
    demoLink: "https://www.instagram.com/tiffanyyan.mov/",
    coverImage: "/images/projects/content-1.png",
    longDescription: "Creativity is very important to me, including design, music, modeling, photography, maker space, and calligraphy.",
    details: { tech: ["Instagram", "LinkedIn", "Notion"] },
    gallery: ["/images/projects/content.png", "/images/projects/content-1.png", "/images/projects/content-2.png", "/images/projects/content-3.png", "/images/projects/content-4.png", "/images/projects/content-5.png"],
    featured: true
  },
  {
    projectName: "Crash Out",
    creatorName: "Amina, Chloe, and Ella",
    track: "software",
    cohort: 3,
    description: "A choice-based mini game that takes place on an island the player crashes onto.",
    demoLink: "/images/projects/crash-out.png",
    coverImage: "/images/projects/crashout.png",
    longDescription: "In order to escape the island, the player must complete tasks, make the right choices, find a special item, and make it to a cave before time runs out.",
    details: { tech: ["Java", "GitHub", "Eclipse"] },
    gallery: ["/images/projects/crashout.png", "/images/projects/crash-out.png"],
    featured: false
  },
  {
    projectName: "Parallel Simulation",
    creatorName: "Benedict Wong",
    track: "hardware",
    cohort: 3,
    description: "AWS cloud architecture that enables parallel simulation applications to transform and analyze data.",
    demoLink: "/images/projects/aws.mp4",
    coverImage: "/images/projects/aws.png",
    longDescription: "AWS cloud architecture that enables parallel simulation applications to transform and analyze data.",
    details: { tech: ["AWS", "Cloud Architecture"] },
    gallery: ["/images/projects/aws.png", "/images/projects/aws.mp4"],
    featured: false
  },
  {
    projectName: "AI Boxer",
    creatorName: "Akshat Mundra",
    track: "wildcard",
    cohort: 3,
    description: "An AI boxer that you can fight against in real time.",
    demoLink: "/images/projects/boxer.mp4",
    coverImage: "/images/projects/boxer1.png",
    longDescription: "An AI boxer that you can fight against in real time.",
    details: { tech: ["Unity"] },
    gallery: ["/images/projects/boxer1.png", "/images/projects/boxer.png", "/images/projects/boxer.mp4"],
    featured: true
  },
  {
    projectName: "CoachT",
    creatorName: "Ojas Kandhare",
    track: "software",
    cohort: 3,
    description: "Uses cameras to advance sports performance - An AI coach for martial arts.",
    demoLink: "www.coacht.xyz",
    coverImage: "/images/projects/coacht.png",
    longDescription: "Gets input from real-time camera feed, monitoring joint and angle information. Plugs in the data into DTW and gives AI feedback.",
    details: { tech: ["DTW", "LLMs", "Computer Vision"] },
    featured: false
  },
];

// ==================== COHORT 2 ====================
export const cohort2Projects: Project[] = [
  {
    projectName: "Chef Lens",
    creatorName: "Ayesha Khan & Mawi Mawi",
    track: "software" as const,
    cohort: 2,
    description: "Streamlining recipe instructions for everyone.",
    demoLink: "/images/projects/chef.mp4",
    coverImage: "/images/projects/chef.png",
    longDescription: "An app that streamlines recipes, with no ads or unecessary backstories.",
    details: { tech: ["Streamlit", "Python", "OpenAI API", "Git"] }, 
    gallery: ["/images/projects/chef.png", "/images/projects/chef1.png", "/images/projects/chef2.png", "/images/projects/chef.mp4", "/images/projects/chef1.mp4"],
    featured: false
  },
  {
    projectName: "Bioinformatics Dashboard",
    creatorName: "Bhavya Krishnan",
    track: "software" as const,
    cohort: 2,
    description: "Helps biologists that were trained classically transition into computational biology/bioinformatics.",
    demoLink: "/images/projects/bio.mp4",
    coverImage: "/images/projects/bio0.png",
    longDescription: "An app to help biologists that were trained classically transition into computational biology/bioinformatics.",
    details: { tech: ["RMarkdown", "R", "ggplot d3", "Hugging Face", "Streamlit"] }, 
    gallery: ["/images/projects/bio.png", "/images/projects/bio1.png", "/images/projects/bio2.png", "/images/projects/bio.mp4"],
    featured: false
  },
  {
    projectName: "CueZine",
    creatorName: "David Kim",
    track: "software" as const,
    cohort: 2,
    description: "Your streamlined food finding friend :)",
    demoLink: "/images/projects/cuezine.mp4",
    coverImage: "/images/projects/cuezine.png",
    longDescription: "A tinder-style way to find places to eat.",
    details: { tech: ["Expo", "AsyncStorage", "React Native", "TypeScript", "Google Places API"] }, 
    gallery: ["/images/projects/cuezine.png", "/images/projects/cuezine1.png", "/images/projects/cuezine2.png", "/images/projects/cuezine3.png", "/images/projects/cuezine.mp4"],
    featured: false
  },
  {
    projectName: "CrowdLight",
    creatorName: "Colton Carroll",
    track: "software" as const,
    cohort: 2,
    description: "Make a holiday lightshow more interactive.",
    demoLink: "/images/projects/light.mp4",
    coverImage: "/images/projects/light.png",
    longDescription: "Make a holiday lightshow more interactive.",
    details: { tech: ["ATTiny85", "ESP32", "HC-12 Transreceiver", "RJ-45 Ethernet Port", "WS2812b LEDs", "Arduino"] }, 
    gallery: ["/images/projects/light.png", "/images/projects/light1.png", "/images/projects/light2.png", "/images/projects/light.mp4"],
    featured: false
  },
  {
    projectName: "Husky ButterWalk",
    creatorName: "Crystal Shen, Katharine Zhang, Jenna Moon-Earle",
    track: "software" as const,
    cohort: 2,
    description: "An Uber app for Husky NightWalk.",
    demoLink: "",
    coverImage: "/images/projects/walk.png",
    longDescription: "An Uber app for Husky NightWalk, where students can track their ride, view estimated wait time, and find meeting point with driver.",
    details: { tech: ["React Native", "Figma", "Expo"] }, 
    gallery: ["/images/projects/walk1.png", "/images/projects/walk.png"],
    featured: false
  },
  {
    projectName: "Vocab Generator for Anki",
    creatorName: "Apolo Garica",
    track: "software" as const,
    cohort: 2,
    description: "A powerful, customizable flashcard application.",
    demoLink: "/images/projects/anki.mp4",
    coverImage: "/images/projects/anki.png",
    longDescription: "A powerful, customizable flashcard application that uses spaced repetition to help users retain information over time.",
    details: { tech: ["LibreTranslate", "PyQt API", "Python", "JavaScript"] }, 
    gallery: ["/images/projects/anki.png", "/images/projects/anki1.png", "/images/projects/anki2.png", "/images/projects/anki3.png"],
    featured: false
  },
  {
    projectName: "Focus Bank",
    creatorName: "Luyang Wu & Varun Atraya",
    track: "software" as const,
    cohort: 2,
    description: "An app to help you lock in.",
    demoLink: "/images/projects/focus.mp4",
    coverImage: "/images/projects/focus.png",
    longDescription: "An app that helps you lock in, forcing you to budget your screen time.",
    details: { tech: ["Expo Go", "React Native", "Swift", "Firebase"] }, 
    gallery: ["/images/projects/focus.png", "/images/projects/focus0.png", "/images/projects/focus1.png", "/images/projects/focus2.png", "/images/projects/focus.mp4"],
    featured: true
  },
  {
    projectName: "AI Social Media Analyst",
    creatorName: "Charlene Lioe",
    track: "software" as const,
    cohort: 2,
    description: "An AI tool designed to help businesses analyze their ad campaigns.",
    demoLink: "/images/projects/analyst.mp4",
    coverImage: "/images/projects/analyst0.png",
    longDescription: "An app that helps you lock in, forcing you to budget your screen time.",
    details: { tech: ["Facebook API", "Python"] }, 
    gallery: ["/images/projects/analyst0.png", "/images/projects/analyst.png", "/images/projects/analyst1.png", "/images/projects/analyst.mp4"],
    featured: false
  },
  {
    projectName: "Beauty of Physics",
    creatorName: "Amy Lu",
    track: "software" as const,
    cohort: 2,
    description: "A physics simulation to help simplify physics.",
    demoLink: "https://drive.google.com/drive/folders/1bkRMeLSiXluXrQAgNKFDOwaPdLIwqthi",
    coverImage: "/images/projects/physics.mp4",
    longDescription: "A physics simulation to help simplify physics - helps you visualize particle movement.",
    details: { tech: ["Three.js"] }, 
    gallery: ["/images/projects/physics2.png", "/images/projects/physics1.png", "/images/projects/physics.mp4"],
    featured: false
  },
  {
    projectName: "File Digest",
    creatorName: "Nico Susanto",
    track: "software" as const,
    cohort: 2,
    description: "Understand your directories.",
    demoLink: "/images/projects/file.mp4",
    coverImage: "/images/projects/file1.png",
    longDescription: "An app that helps you summarize and understand your directory files.",
    details: { tech: ["TKinter", "Python", "Gemini AI API"] }, 
    gallery: ["/images/projects/file1.png", "/images/projects/file0.png", "/images/projects/file2.png", "/images/projects/file3.png"],
    featured: false
  },
  {
    projectName: "AI + Healthcare",
    creatorName: "Smriti Kalahalla, Jia Ruparel, Alba Navarro, and Stephanie Lau",
    track: "software" as const,
    cohort: 2,
    description: "An website that identifies an injury based off image recognition.",
    demoLink: "/images/projects/health.mp4",
    coverImage: "/images/projects/health.png",
    longDescription: "The website will quickly identify an injury from an image, and offer instructions on how to treat it.",
    details: { tech: ["TensorFlow", "Keras sequential model", "CNNs", "Python"] }, 
    gallery: ["/images/projects/health.png", "/images/projects/health1.png", "/images/projects/health2.png","/images/projects/health3.png", "/images/projects/health4.png","/images/projects/health5.png"],
    featured: false
  },
  {
    projectName: "Pinpots",
    creatorName: "Claire Li",
    track: "software" as const,
    cohort: 2,
    description: "Upload pictures of cool plants you see, and mark it on your map.",
    demoLink: "https://pinpots.onrender.com/",
    coverImage: "/images/projects/pots0.png",
    longDescription: "Upload pictures of cool plants you see, and mark it on your map. Share these plants with your friends/the public, or choose to keep it private.",
    details: { tech: ["Google Cloud", "PyTorch", "React"] }, 
    gallery: ["/images/projects/pots0.png", "/images/projects/pots.png", "/images/projects/pots2.png", "/images/projects/pots3.png", "/images/projects/pots.mp4"],
    featured: false
  },
  {
    projectName: "Vision",
    creatorName: "Nitya Kakulamarri & Maggie Lam",
    track: "software" as const,
    cohort: 2,
    description: "An application that generates an audio description of a visual to assist visually impaired individuals.",
    demoLink: "/images/projects/vision.mp4",
    coverImage: "/images/projects/vision.png",
    longDescription: "An application that uses artificial intelligence to automatically generates an audio description of a visual to assist visually impaired individuals.",
    details: { tech: ["Swift", "Python", "TensorFlow", "PyTorch", "HuggingFace"] }, 
    gallery: ["/images/projects/vision.png", "/images/projects/vision0.png", "/images/projects/vision1.png", "/images/projects/vision.mp4"],
    featured: false
  },
  {
    projectName: "Wormodoro",
    creatorName: "Kaitlyn Ellington, Farrel Sudrajat, Sunny Tian, and Ricardo Torres Arevalo",
    track: "software" as const,
    cohort: 2,
    description: "A study timer designed to reduce distractions, enhance concentration, and optimize productivity.",
    demoLink: "https://www.youtube.com/watch?v=wp7I6YJosyA&t=11s",
    coverImage: "/images/projects/worm0.png",
    longDescription: "A study timer designed to reduce distractions, enhance concentration, and optimize productivity.",
    details: { tech: ["React", "Figma"] }, 
    gallery: ["/images/projects/worm.png", "/images/projects/worm0.png", "/images/projects/worm1.png", "/images/projects/worm2.png"],
    featured: false
  },
  {
    projectName: "InstaGrocery",
    creatorName: "Anushka Malpani",
    track: "software" as const,
    cohort: 2,
    description: "An app that makes grocery shopping easy, efficient, and cheap.",
    demoLink: "",
    coverImage: "/images/projects/grocery.png",
    longDescription: "An app that makes grocery shopping easy, efficient, and cheap. InstaGrocery lets you make a grocery list and find stores near you that have those products currently available while also giving you the best deals!",
    details: { tech: ["Streamlit", "Kroger API", "IPinfo.io API"] }, 
    gallery: ["/images/projects/grocery0.png", "/images/projects/grocery.png", "/images/projects/grocery1.png"],
    featured: false
  },
  {
    projectName: "Fantasy Football Winners",
    creatorName: "Benjamin Epstein",
    track: "software" as const,
    cohort: 2,
    description: "Makes weekly projections for each player's stats and uses these to project their season.",
    demoLink: "/images/projects/football.mp4",
    coverImage: "/images/projects/football3.png",
    longDescription: "A fantasy football winner prediction that makes weekly projections for each player's stats and uses these to project their season. There is also a trade machine where you can input to sides of a trade and using the projects and winner is announced.",
    details: { tech: ["Python", "LSTM Model"] }, 
    gallery: ["/images/projects/football.png", "/images/projects/football1.png", "/images/projects/football0.png", "/images/projects/football2.png", "/images/projects/football.mp4"],
    featured: false
  },
  {
    projectName: "Function",
    creatorName: "Agastya Mongia",
    track: "software" as const,
    cohort: 2,
    description: "A holistic event management application for RSOs at UW.",
    demoLink: "",
    coverImage: "/images/projects/function.png",
    longDescription: "A holistic event management application for RSOs at UW.",
    details: { tech: ["React", "Expo", "Supabase", "Flutter", "Postgres"] }, 
    gallery: ["/images/projects/function.png", "/images/projects/function1.png", "/images/projects/function2.png", "/images/projects/function3.png", "/images/projects/function4.png"],
    featured: false
  },
  {
    projectName: "UEngage",
    creatorName: "Vivaan Kothari, Aryaman Tandon, Aarnav Gogri, and Vihaan Mangat",
    track: "software" as const,
    cohort: 2,
    description: "Your gateway to UW club events!",
    demoLink: "",
    coverImage: "/images/projects/engage.png",
    longDescription: "An app that allows you to find, create, and join clubs + events.",
    details: { tech: ["React", "Firebase", "TypeScript", "HTML", "CSS", "Figma"] }, 
    gallery: ["/images/projects/engage.png", "/images/projects/engage1.png", "/images/projects/engage2.png", "/images/projects/engage3.png"],
    featured: false
  },
  {
    projectName: "MenuMaster",
    creatorName: "Vrinda Rathi",
    track: "software" as const,
    cohort: 2,
    description: "An app that stores your favorite meals and recipes, helping generate a weekly menu and grocery list.",
    demoLink: "/images/projects/menu.mp4",
    coverImage: "/images/projects/menu.png",
    longDescription: "An app that stores your favorite meals and recipes, helping generate a weekly menu and grocery list.",
    details: { tech: ["React", "Node.js", "Express.js", "MongoDB"] }, 
    gallery: ["/images/projects/menu2.png", "/images/projects/menu3.png", "/images/projects/menu1.png", "/images/projects/menu.mp4"],
    featured: false
  },
  {
    projectName: "Careerate",
    creatorName: "Garv Seth",
    track: "software" as const,
    cohort: 2,
    description: "Accelerate your career.",
    demoLink: "",
    coverImage: "/images/projects/career0.png",
    longDescription: "An app that helps you accelerate your career, through smart job matching, AI resume and cover letter generation, autofilling job applications, and career analyses.",
    details: { tech: ["Swift", "Python"] }, 
    gallery: ["/images/projects/career1.png", "/images/projects/career0.png", "/images/projects/career.png", "/images/projects/career2.png"],
    featured: false
  },
  {
    projectName: "carpetCare Pro",
    creatorName: "Miriam Castillo Romero",
    track: "software" as const,
    cohort: 2,
    description: "An app that helps small businesses - providing all tools in one place.",
    demoLink: "",
    coverImage: "/images/projects/carpet0.png",
    longDescription: "An app that helps small businesses - providing all the necessary tools in one place.",
    details: { tech: ["Figma"] }, 
    gallery: ["/images/projects/carpet0.png", "/images/projects/carpet.png", "/images/projects/carpet1.png", "/images/projects/carpet2.png", "/images/projects/carpet3.png", "/images/projects/carpet4.png"],
    featured: false
  },
  {
    projectName: "InsulInfo",
    creatorName: "Raghav Thyagarajan, Dylan Song, Joonho Choi, and Nathan Lin",
    track: "hardware" as const,
    cohort: 2,
    description: "Tracks glucose levels and gives insights based on its trends.",
    demoLink: "",
    coverImage: "/images/projects/insulin.png",
    longDescription: "Tracks glucose levels and gives insights based on its trends. Helps diabetics control their glucose levels, and consists of both hardware and software.",
    details: { tech: ["Python", "LibreLinkUp", "MySQL", "Figma"] }, 
    gallery: ["/images/projects/insulin.png", "/images/projects/insulin2.png", "/images/projects/insulin3.png", "/images/projects/insulin1.png", "/images/projects/insulin4.png", ],
    featured: false
  }
];

// ==================== COHORT 0 ====================
export const cohort0Projects: Project[] = [
  {
    projectName: "Bobby",
    creatorName: "Carter Swartout & Andrew Edwards",
    track: "hardware",
    cohort: 0,
    description: "A homemade Alexa and digital assistant that incorporates hardware, software, and gen AI.",
    demoLink: "/images/projects/bobby.mp4",
    coverImage: "/images/projects/bobby.png",
    longDescription: "A homemade Alexa and digital assistant that incorporates hardware, software, and gen AI.",
    details: { tech: ["Python", "OpenAI API", "Raspberry Pi 4B", "Lepist Model LE2103"] },
    gallery: ["/images/projects/bobby.png", "/images/projects/bobby1.png", "/images/projects/bobby2.png", "/images/projects/bobby.mp4"],
    featured: true
  },
  {
    projectName: "Comic App",
    creatorName: "Katherine Palevich",
    track: "software",
    cohort: 0,
    description: "An app that displays and xkcd comic based on the users input.",
    demoLink: "/images/projects/xkcd.mp4",
    coverImage: "/images/projects/xkcd.mp4",
    longDescription: "An app that displays and xkcd comic based on the users input.",
    details: { tech: ["Swift", "XCode"] },
    gallery: ["/images/projects/xkcd2.png", "/images/projects/xkcd.png", "/images/projects/xkcd.mp4"],
    featured: false
  },
  {
    projectName: "MusicMatch",
    creatorName: "Srishti Singh, Isha Jagadish, and Sneha Murali",
    track: "software",
    cohort: 0,
    description: "Connect with other people with similar music taste to yourself!",
    demoLink: "https://ec2-3-17-24-47.us-east-2.compute.amazonaws.com/",
    coverImage: "/images/projects/music0.png",
    longDescription: "An app that helps you connect with other people that have similar music taste to yourself.",
    details: { tech: ["AWS Cloud", "HTML", "CSS", "JavaScript"] },
    gallery: ["/images/projects/music0.png", "/images/projects/music.png", "/images/projects/music2.png"],
    featured: false
  },
  {
    projectName: "chenthetutor",
    creatorName: "Chendur Jayavelu",
    track: "creatives",
    cohort: 0,
    description: "A project to grow my ACT Math TikTok.",
    demoLink: "https://www.tiktok.com/@chenthetutor",
    coverImage: "/images/projects/tutor0.png",
    longDescription: "A project to grow my ACT Math TikTok by posting one 30-90 second video a day.",
    details: { tech: ["iPad", "TikTok"] },
    gallery: ["/images/projects/tutor0.png", "/images/projects/tutor.png", "/images/projects/tutor1.png", "/images/projects/tutor.mp4"],
    featured: false
  },
  {
    projectName: "MedCheck",
    creatorName: "Danielle Maddox",
    track: "software",
    cohort: 0,
    description: "A drug interaction checker for physicians.",
    demoLink: "/images/projects/medcheck.mp4",
    coverImage: "/images/projects/medcheck.png",
    longDescription: "A drug interaction checker to notify physicians if the medications they prescribe have severe interactions with the patients existing medications.",
    details: { tech: ["InteliJ", "Canva"] },
    gallery: ["/images/projects/medcheck.png", "/images/projects/medcheck1.png", "/images/projects/medcheck4.png", "/images/projects/medcheck2.png", "/images/projects/medcheck3.png", "/images/projects/medcheck.mp4"],
    featured: false
  },
  {
    projectName: "Habit Builder",
    creatorName: "Emily Kang",
    track: "software",
    cohort: 0,
    description: "A structured place for habits, allowing you to connect, log, and visualize your results.",
    demoLink: "",
    coverImage: "/images/projects/habits0.png",
    longDescription: "A structured place for habits, allowing you to connect, log, and visualize your results. Based on Atomic Habits, Habit Builder allows you to learn new habits easier is.",
    details: { tech: ["Expo", "React Native", "Vite", "TypeScript", "Figma"] },
    gallery: ["/images/projects/habits.png", "/images/projects/habits1.png"],
    featured: false
  },
  {
    projectName: "ClearVote",
    creatorName: "Anaya Pandit, Robert Luiten, Joey Laurent, and David Schultz",
    track: "software",
    cohort: 0,
    description: "A web app that simplifies the voting process to increase voter turnout.",
    demoLink: "https://clearvote.info/",
    coverImage: "/images/projects/vote.png",
    longDescription: "ClearVote shows all candidate information in one spot with full transparency, and brings focus back to the community.",
    details: { tech: ["Python", "React", "Next.js", "Radix", "GeoPandas", "Figma"] },
    gallery: ["/images/projects/vote.png", "/images/projects/vote1.png", "/images/projects/vote2.png", "/images/projects/vote3.png", "/images/projects/vote4.png", "/images/projects/vote5.png", "/images/projects/vote6.png"],
    featured: true
  },
  {
    projectName: "Us And AI: The Progress of AI and How We Will Stay as Humans",
    creatorName: "Jintae Cho",
    track: "creatives",
    cohort: 0,
    description: "A nonfiction book about AI and humanity.",
    demoLink: "",
    coverImage: "/images/projects/book.png",
    longDescription: "Worked on my book by writing 20,000 words in the matter of 6 weeks. Tried to perfect my writing skill by mostly working on the consistency.",
    details: { tech: ["Microsoft Word"] },
    gallery: ["/images/projects/book.png", "/images/projects/book2.png"],
    featured: false
  },
  {
    projectName: "EasyLeasy",
    creatorName: "Ankith Tunuguntla & Praveer Jain",
    track: "software",
    cohort: 0,
    description: "A UW centric apartment finder which tries to solve the roommate match problem.",
    demoLink: "",
    coverImage: "/images/projects/lease.png",
    longDescription: "A UW centric apartment finder which tries to solve the roommate match problem. You make a profile and match with other people based on interests and specifications of apartments.",
    details: { tech: ["React", "HTML", "CSS", "JavaScript", "Figma"] },
    gallery: ["/images/projects/lease.png", "/images/projects/lease1.png"],
    featured: false
  },
  {
    projectName: "Ripple: UW Marketplace",
    creatorName: "Will Hunt",
    track: "software",
    cohort: 0,
    description: "A student based second-hand marketplace.",
    demoLink: "/images/projects/market.mp4",
    coverImage: "/images/projects/market.mp4",
    longDescription: "A platform for UW students to sell their things to each other.",
    details: { tech: ["React", "Firebase", "Chakra"] },
    gallery: ["/images/projects/market0.png", "/images/projects/market.png", "/images/projects/market.mp4"],
    featured: false
  },
  {
    projectName: "EduCon",
    creatorName: "Srimedha Thummala",
    track: "software",
    cohort: 0,
    description: "A common platform for students to connect.",
    demoLink: "",
    coverImage: "/images/projects/edu1.png",
    longDescription: "A central platform where students can connect with other students of similar backgrounds and interests. Through these relationships, students can build their education and knowledge beyond their curriculum.",
    details: { tech: ["Figma", "React"] },
    gallery: ["/images/projects/edu1.png", "/images/projects/edu.png"],
    featured: false
  },
  {
    projectName: "Wellness + Content Creation",
    creatorName: "Anika Tara Rao",
    track: "creatives",
    cohort: 0,
    description: "Sharing my journey in college.",
    demoLink: "https://www.youtube.com/@tarastemples",
    coverImage: "/images/projects/well0.png",
    longDescription: "Created content of my college wellness journey. Released multiple post in the instagram and tiktok. I even got a chance to record my first youtube video and continue releasing episodes for my podcast: “The Mango Tree Podcst”.",
    details: { tech: ["Instagram", "TikTok", "Youtube", "Spotify"] },
    gallery: ["/images/projects/well.png", "/images/projects/well1.png", "/images/projects/well2.png", "/images/projects/well3.png", "/images/projects/well4.png"],
    featured: false
  },
  {
    projectName: "Research: Personality by Shopping Habits",
    creatorName: "Reuben Ailin Santoso",
    track: "software",
    cohort: 0,
    description: "Research aimed to match the consumer habits and the personalities.",
    demoLink: "",
    coverImage: "/images/projects/receipt1.png",
    longDescription: "Worked on receipt aimed computer vision to research the relationship between consumer habits and personality.",
    details: { tech: ["OpenCV", "PyTorch", "Pytesseract"] },
    gallery: ["/images/projects/receipt.png", "/images/projects/receipt1.png", "/images/projects/receipt2.png"],
    featured: false
  },
  {
    projectName: "Scheduler + Mindharbour",
    creatorName: "Vani Agarwal",
    track: "software",
    cohort: 0,
    description: "A notion replacer with a better scheduling experience and an idea logger.",
    demoLink: "",
    coverImage: "/images/projects/schedule.png",
    longDescription: "An app to organize your schedule, tasks, and ideas. Keeps track of task priority, mood, habits, and thoughts.",
    details: { tech: ["Figma", "React"] },
    gallery: ["/images/projects/schedule.png"],
    featured: false
  },
  {
    projectName: "CINEM.AI",
    creatorName: "Chaitanya Sekhar",
    track: "software",
    cohort: 0,
    description: "A movie recommendation app.",
    demoLink: "",
    coverImage: "/images/projects/cinema0.png",
    longDescription: "A personalized movie search with filter for genres, actors, languages, etc. Explore, share, and customize your cinematic journey through personalized suggestions and movie discovery.",
    details: { tech: ["Webflow"] },
    gallery: ["/images/projects/cinema.png", "/images/projects/cinema1.png", "/images/projects/cinema2.png", "/images/projects/cinema0.png", "/images/projects/cinema3.png", "/images/projects/cinema4.png"],
    featured: false
  },
  {
    projectName: "Spark Royalty",
    creatorName: "Isaac Dyor, Sam, and Clark Jones",
    track: "software",
    cohort: 0,
    description: "The world's first royalty based freelancing marketplace.",
    demoLink: "https://sparkroyalty2.vercel.app/",
    coverImage: "/images/projects/spark.png",
    longDescription: "The world's first royalty based freelancing marketplace for founders and investors.",
    details: { tech: ["React", "TailwindCSS", "Shadcn", "Prisma", "tRPC", "Supabase"] },
    gallery: ["/images/projects/spark.png"],
    featured: false
  },
  {
    projectName: "Personal Website",
    creatorName: "Tina Lai",
    track: "software",
    cohort: 0,
    description: "Build my personal website with light/dark themes.",
    demoLink: "https://teena1313.github.io/teena1313.githubio/index.html",
    coverImage: "/images/projects/personal1.png",
    longDescription: "Build my personal website with light/dark themes.",
    details: { tech: ["Godot", "HTML", "CSS", "Javascript"] },
    gallery: ["/images/projects/personal1.png", "/images/projects/personal.png"],
    featured: false
  },
  {
    projectName: "Galleria",
    creatorName: "Omar Ahmed",
    track: "software",
    cohort: 0,
    description: "Digitizing real-world art.",
    demoLink: "",
    coverImage: "/images/projects/galleria0.png",
    longDescription: "Galleria empowers all artists to digitize their paintings (Artokens), collect royalties, and control all future sales.",
    details: { tech: ["Next.js", "Express.js", "Wikiart Dataset", "LEDITS++", "AWS ABM", "Meta Mask", "Opensea", "Hugging Face"] },
    gallery: ["/images/projects/galleria.png", "/images/projects/galleria1.png", "/images/projects/galleria2.png"],
    featured: false
  },
  {
    projectName: "ClinicChatBot",
    creatorName: "Kevin Xiao",
    track: "software",
    cohort: 0,
    description: "A web chatbot for medical clinics and hospitals to provide the most relevant and accurate information to patients quickly.",
    demoLink: "",
    coverImage: "/images/projects/chatbot1.png",
    longDescription: "A web chatbot using LLMs for medical clinics and hospitals to provide the most relevant and accurate information to patients quickly, expediting the process of finding medical information online.",
    details: { tech: ["HTML", "CSS", "JavaScript", "Python", "OpenAI API", "Flask", "Pandas"] },
    gallery: ["/images/projects/chatbot.png", "/images/projects/chatbot1.png", "/images/projects/chatbot2.png", "/images/projects/chatbot3.png"],
    featured: false
  },
  {
    projectName: "Logarithm",
    creatorName: "Beta Chen & Kai Green",
    track: "software",
    cohort: 0,
    description: "An app that helps people learn what behavior additions/removals work best for them.",
    demoLink: "",
    coverImage: "/images/projects/log.png",
    longDescription: "Logarithm is an app that helps people learn what behavior additions/removals work best for them by tracking the results of different behaviors by allowing users do the A/B tests on themselves.",
    details: { tech: ["Figma", "XCode"] },
    gallery: ["/images/projects/log.png", "/images/projects/log1.png", "/images/projects/log2.png", "/images/projects/log3.png", "/images/projects/log4.png", "/images/projects/log5.png", "/images/projects/log6.png", "/images/projects/log7.png"],
    featured: false
  },
  {
    projectName: "ResourceRoute App",
    creatorName: "Thea Klein-Balajee",
    track: "software",
    cohort: 0,
    description: "An app that helps unhoused people find needed resources in the UW area like medicine, food, and shelter.",
    demoLink: "",
    coverImage: "/images/projects/resource.png",
    longDescription: "An app that helps unhoused people find needed resources in the UW area like medicine, food, and shelter.",
    details: { tech: ["Figma"] },
    gallery: ["/images/projects/resource.png"],
    featured: false
  },
  {
    projectName: "Husky Match",
    creatorName: "Enrico Pratama, Melvin Chia, and Winston Wihono",
    track: "creatives",
    cohort: 0,
    description: "A product roadmap for a UW centered dating app.",
    demoLink: "",
    coverImage: "/images/projects/match.png",
    longDescription: "A product roadmap for a UW centered dating app, making it more personalized and with enhanced matching.",
    details: { tech: ["Kotlin", "Python", "Figma"] },
    gallery: ["/images/projects/match.png", "/images/projects/match1.png", "/images/projects/match2.png", "/images/projects/match3.png", "/images/projects/match4.png", "/images/projects/match5.png", "/images/projects/match6.png", "/images/projects/match7.png"],
    featured: false
  },
  {
    projectName: "D.O.T.",
    creatorName: "Saara Uthmaan",
    track: "software",
    cohort: 0,
    description: "A TODO web app to put as a project for my portfolio.",
    demoLink: "",
    coverImage: "/images/projects/dot1.png",
    longDescription: "Developing my personal portfolio, and including a TODO web app to put as a project.",
    details: { tech: ["JavaScript", "APIs", "Figma"] },
    gallery: ["/images/projects/dot.png"],
    featured: false
  },
  {
    projectName: "Better Grades",
    creatorName: "Jeffrey Lan",
    track: "software",
    cohort: 0,
    description: "A standardized way of viewing course information and materials.",
    demoLink: "https://www.youtube.com/watch?v=GK-7_3BMwDs",
    coverImage: "/images/projects/grades7.png",
    longDescription: "A browser extension that transforms your new tabs into a powerful and aesthetic study dashboard infused with your course information and materials from Canvas.",
    details: { tech: ["Shadcn", "Framer Motion", "TailwindCSS", "React", "TypeScript", "Vite"] },
    gallery: ["/images/projects/grades0.png", "/images/projects/grades2.png", "/images/projects/grades3.png", "/images/projects/grades.png", "/images/projects/grades1.png", "/images/projects/grades5.png", "/images/projects/grades7.png"],
    featured: false
  },
];

// ==================== HELPER FUNCTIONS ====================

// Combined array of all projects
export const projects: Project[] = [
  ...cohort4Projects,
  ...cohort3Projects,
  ...cohort2Projects,
  ...cohort0Projects,
];

// Get only featured projects
export const getFeaturedProjects = (): Project[] => {
  return projects.filter(project => project.featured === true);
};

// Get projects by cohort
export const getProjectsByCohort = (cohort: Cohort): Project[] => {
  switch(cohort) {
    case 4: return cohort4Projects;
    case 3: return cohort3Projects;
    case 2: return cohort2Projects;
    case 0: return cohort0Projects;
    default: return [];
  }
};